### PR TITLE
Add: improved typing

### PR DESCRIPTION
**Pull request by nallon**
code auto-formated by "black"

### CODE REVIEW

**Comment by david-lev** [comment]
Hi @nallon,

Thanks for your interest in contributing to this project. I appreciate your willingness to help, but I'm afraid I'm going to have to reject this pull request.

The changes you've proposed are just formatting changes, and they're not necessary. The formatting is already consistent with the rest of the repo.

I would encourage you to focus on making more substantive changes. You can see [here](https://github.com/david-lev/pywa#%EF%B8%8F-todo) the list of todos planned for the project.

I invite you to join the pywa discussion group on Telegram https://t.me/pywachat

Thanks again for your interest :)

**Comment by nallon** [comment]
image

As you can see in the picture above the changes were more than formatting changes. The intention was to improve the typing annotation for more consistent variable signatures in the code base.

**Comment by david-lev** [comment]
Ok I understand (Pycharm has different type checker)
Just make sure that the typing style matches the rest of the project (`Iterable | None` instead of `Optional[x]`)

**Comment by nallon** [comment]
> typing style

done!

**Pull request merged**
